import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import {withAuthAndPermission} from '../components/Auth';

import Form from '@/components/Form';
import PostFeed from '@/components/PostFeed';

const Home = () => {
  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header label={'Home'}/>
        <Form placeholder="What's happening?"></Form>
        <PostFeed></PostFeed>
      </main>
    </>
  )
}

export default withAuthAndPermission(Home, ['home']);